FROM debian:bullseye-slim AS build-image

#ARG MODEL
#ENV MODEL=${MODEL}
RUN pwd;ls -la

COPY ./download.sh ./

# Install build dependencies
RUN apt-get update && \
    apt-get install -y git-lfs

RUN chmod +x *.sh && \
    ./download.sh && \
    rm *.sh

# Grab a fresh copy of the Python image
FROM python:3.11-slim

#ARG MODEL

RUN mkdir -p ${MODEL}
COPY --from=build-image ${MODEL} ${MODEL}
RUN pip install --upgrade pip setuptools && \
    pip install --no-cache-dir open-text-embeddings[server]